[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/deckarep/golang-set"
  version = "1.7.1"

[[constraint]]
  name = "code.cloudfoundry.org/go-loggregator"
  version = "7.1.0"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/tps"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/goshims"

[[constraint]]
  name = "github.com/cloudfoundry-incubator/credhub-cli"
  version = "2.1.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
